id: P000361
initial_creation_type: ocr
created_at: 16/03/2020
last_modified_at: 2021-12-16 15:35:56.262688
source_metadata:
  id: bdr:W17788
  title: མན་ངག་རིན་ཆེན་འབྱུང་གནས
  author: ''
  volumes:
    fe24f1ca48f7478aa50389bc1db122aa:
      image_group_id: I4797
      title: ''
      volume_number: 1
      total_pages: 954
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
